[package]
name = "blackbox_arena_contracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.17.0"

[dev-dependencies]
snforge_std = "0.59.0"
assert_macros = "2.17.0"

[[target.starknet-contract]]
casm = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "snforge test"

